name: TI IOC Automation - FETCH

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  download-and-commit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download 14-day log file
      run: |
        curl -o honeypot/ssh/iocs-14d.csv https://prod.fileserv03.supreme.sh/pkc/ssh/logs/honey-14d.log

    - name: Download 30-day log file
      run: |
        curl -o honeypot/ssh/iocs-30d.csv https://prod.fileserv03.supreme.sh/pkc/ssh/logs/honey-30d.log

    - name: Attack Pattern Log import
      run: |
        curl -o honeypot/ssh/attack-pattern/full-14d.csv https://prod.fileserv03.supreme.sh/pkc/ssh/logs/attack_pattern_14d.json

    - name: Commit and push if there are changes
      run: |
        git config --global user.name 'ntwrite [via GH Actions]'
        git config --global user.email 'cam@supreme.sh'
        git add honeypot/ssh/iocs-14d.csv honeypot/ssh/iocs-30d.csv
        git diff --staged --quiet || git commit -m "Update Honeypot IOC files"
        git push || echo "No changes to commit"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
